-- STUDY MATERIAL: video entitlement + private storage
-- Run this once in Supabase SQL Editor.

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric(10,2) not null default 0,
  storage_path text,
  thumbnail_url text,
  active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.video_content (
  video_id bigint primary key references public.videos(id) on delete cascade,
  video_path text not null
);

-- If the videos table already existed, add the column safely.
alter table public.videos
  add column if not exists storage_path text;

-- Permanent entitlement is represented by an approved purchase row.
alter table public.purchases
  add column if not exists video_id bigint references public.videos(id) on delete cascade;

-- Allow either a product or a video purchase.
alter table public.purchases
  drop constraint if exists purchases_product_or_video_check;

alter table public.purchases
  add constraint purchases_product_or_video_check
  check (
    (product_id is not null and video_id is null)
    or (product_id is null and video_id is not null)
  );

-- Admin helper.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- RLS
alter table public.videos enable row level security;
alter table public.video_content enable row level security;
alter table public.purchases enable row level security;

drop policy if exists "Anyone can view active videos" on public.videos;
create policy "Anyone can view active videos"
on public.videos for select
using (active = true or public.is_admin());

drop policy if exists "Admins manage videos" on public.videos;
create policy "Admins manage videos"
on public.videos for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Approved users can view video content" on public.video_content;
create policy "Approved users can view video content"
on public.video_content for select to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.purchases p
    where p.user_id = auth.uid()
      and p.video_id = video_content.video_id
      and p.status = 'approved'
  )
);

drop policy if exists "Admins manage video content" on public.video_content;
create policy "Admins manage video content"
on public.video_content for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Purchases: user can create/view own, admin can update.
drop policy if exists "Users can create own purchase" on public.purchases;
create policy "Users can create own purchase"
on public.purchases for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can view own purchases" on public.purchases;
create policy "Users can view own purchases"
on public.purchases for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins manage purchases" on public.purchases;
create policy "Admins manage purchases"
on public.purchases for update to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Private Storage bucket policies.
-- The bucket named "videos" must already exist and be PRIVATE.
drop policy if exists "Admins can upload videos" on storage.objects;
create policy "Admins can upload videos"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'videos' and public.is_admin()
);

drop policy if exists "Admins can update videos" on storage.objects;
create policy "Admins can update videos"
on storage.objects for update to authenticated
using (bucket_id = 'videos' and public.is_admin())
with check (bucket_id = 'videos' and public.is_admin());

drop policy if exists "Admins can delete videos" on storage.objects;
create policy "Admins can delete videos"
on storage.objects for delete to authenticated
using (bucket_id = 'videos' and public.is_admin());

-- Approved users may read objects in the videos bucket.
-- The application only requests a short-lived signed URL after checking
-- the permanent approved purchase entitlement.
drop policy if exists "Approved users can read videos" on storage.objects;
create policy "Approved users can read videos"
on storage.objects for select to authenticated
using (
  bucket_id = 'videos'
  and (
    public.is_admin()
    or exists (
      select 1
      from public.videos v
      join public.purchases p on p.video_id = v.id
      where p.user_id = auth.uid()
        and p.status = 'approved'
        and v.storage_path = storage.objects.name
    )
  )
);
