create table if not exists profiles (
  id uuid primary key,
  name text,
  email text unique,
  created_at timestamptz default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null default 0,
  content_url text,
  type text not null default 'ebook',
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  product_id bigint references products(id),
  payment_ref text,
  amount numeric not null,
  status text not null default 'pending',
  created_at timestamptz default now()
);

create table if not exists ncert_classes (
  id bigint generated by default as identity primary key,
  class_number int not null,
  subject text,
  title text,
  official_url text,
  active boolean default true
);
